<?php 
/*
 * © 2015 LOGIPAM services / www.logipam.com siges@logipam.com et contributeurs (voir www.logipam.com)
 * 
 * This file is part of SIGES.

    SIGES is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    SIGES is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SIGES.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

?>
<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  0 => '',
  '<b>(1)Right overlapping! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '',
  '<b>(2)Left overlapping! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '',
  '<b>(3)Cet intervalle d\'heure n\'est pas disponible en ce jour</b>.' => '',
  '<b>(4)Cet intervalle d\'heure n\'est pas disponible en ce jour</b>.' => '',
  '<b>(ERROR_1)Chevauchement a droite! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '',
  '<b>(ERROR_2)Chevauchement a gauche! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '',
  '<b>(ERROR_3)Cet intervalle d\'heure n\'est pas disponible en ce jour</b>.' => '',
  '<b>(ERROR_4)Cet intervalle d\'heure n\'est pas disponible en ce jour</b>.' => '',
  '<b>(ERROR_5)Cet intervalle d\'heure est hors vacation__________________________</b>.' => '',
  '<b>ERROR_1 : The choosen teacher is not available at this time. </b>.' => '',
  '<b>ERROR_2 : The choosen teacher is not available at this time. </b>.' => '',
  '<b>ERROR_3 : The choosen teacher is not available at this time. </b>.' => '',
  '<b>ERROR_4 : The choosen teacher is not available at this time. </b>.' => '',
  'Relation widget is not able to instantiate the given Model' => '',
  'The table "{table}" for active record class "{class}" cannot be found in the database.' => '',
  'Widget "Relation" has been run without fields Option(string or array)' => '',
  '{attribute} must be greater than "{compareValue}".' => '',
  '{class} does not have attribute "{attribute}".' => '',
  '<b>(1)Chevauchement a droite! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '@@@@',
  '<b>(1)Le Professeur ou l\'intervalle d\'heure choisi n\'est pas disponible </b>.' => '@@@@',
  '<b>(2)Chevauchement a gauche! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '@@@@',
  '<b>(2)Le Professeur ou l\'intervalle d\'heure choisi n\'est pas disponible </b>.' => '@@@@',
  '<b>(3)Le Professeur ou l\'intervalle d\'heure choisi n\'est pas disponible </b>.' => '@@@@',
  '<b>(4)Le Professeur ou l\'intervalle d\'heure choisi n\'est pas disponible </b>.' => '@@@@',
  '<b>Avalement a gauche! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '@@@@',
  '<b>Ce cours est deja disponible pour cet intervalle d\'heure en ce jour</b>.' => '@@@@',
  '<b>Ce professeur est occupe ailleurs pour cette intervalle d\'heure </b>.' => '@@@@',
  '<b>Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '@@@@',
  '<b>Cet intervalle d\'heure n\'est pas disponible pour ce Cours</b>.' => '@@@@',
  '<b>Chevauchement a droite! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '@@@@',
  '<b>Chevauchement a gauche! Cet intervalle d\'heure n\'est pas disponible en ce jour pour ce Cours</b>.' => '@@@@',
);
